name: Docker Image CI

on:
  push:
    branches: '*'
    tags: '*'
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Build
      run: make docker-build

    - name: Docker Push
      run: |
        echo ${{ github.token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        make docker-push
      if: startsWith(github.ref, 'refs/tags/')
